### ISSUE TITLE
ASMFMT_VSI

### ISSUE THREAD

**Issue by salva-rczero** [salva-rczero/hyperion-sharedvfp#1]
@JamesWekel, I found a minor bug at opcode.c:

```
IPRINT_FUNC(ASMFMT_VSI);
    int v1, d2, b2, i3;
    UNREFERENCED(regs);
    v1 = ((inst[4] >> 4) & 0x0F) | ((inst[4] & 0x08) << 1);

```
should be
`    v1 = ((inst[4] >> 4) & 0x0F) | ((inst[4] & 0x01) << 4);`

Regards.

**Comment by JamesWekel** [comment]
Thanks. I'll include an update in my next pull request to Fish.

Jim

**Comment by salva-rczero** [comment]
ok
